apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::846533034013:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1WAUBI5PPIXK8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::846533034013:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-29T02:51:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1577"
  uid: bbd0bd56-9c5a-4f83-bb2d-2f0c2de4b2f6
